### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by mertkantaroglu** [lenkon/JavaScript-Capstone#29]
You made a great job so far by implementing required functionalities to the project. In addition there might be little changes in:

- [ ] You can work on the design to improve it.
- [ ] You can mark the completed issues to follow the production progress easier.

**Comment by lenkon** [comment]
Hi @mertkantaroglu ,

Thanks for the feedback. I have made the necessary changes.

Best Regards,
K. Inoulen Shanongba
